# Generated by Django 6.0.7 on 2026-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_category_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='TEMP-SKU', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='TEMP-BARCODE', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=20),
        ),
    ]
